### ISSUE TITLE
Uncaught TypeError: window._LRLogger is not a constructor

### ISSUE THREAD

**Issue by cmckni3** [LogRocket/logrocket#12]
Relevant code

```
  script.onload = function () {
    instance.onLogger(new window._LRLogger({
      sdkVersion: "0.6.17" // eslint-disable-line no-undef
    }));
  };
```

I believe this is the redux logger and happens when the redux devtools aren't installed.

**Comment by markhicken** [comment]
Seeing the same thing here but it's Brave browser blocking something. Shields down and the error goes away.
