### ISSUE TITLE
Node was not found

### ISSUE THREAD

**Issue by PhilippeTrounev** [LogRocket/logrocket#13]
Sentry caught this strange bug in logrocket today. 
NotFoundError
Node was not found
/LogRocket.min.js in o at line 2:24507
/* Acknowledgements: https://logrocket.com/open-source/ */
{snip} -;)o[i]=a?r.wrap(e,arguments[i]):arguments[i];try{return t.apply(this,o)}catch(t){throw r._ignoreNextOnError(),r.captureException(u.default. {snip}

Not sure what this is. But I don't see a video for this session... Seems to be intermittent.

**Comment by eranimo** [comment]
This doesn't appear to be coming from LogRocket.
