### ISSUE TITLE
Including logrocket npm package breaks our existing SourceMaps

### ISSUE THREAD

**Issue by wiborn** [LogRocket/logrocket#14]
We are trying to use logrocket in our react application but when including it in our project it results in our sourcemaps not being able to be parsed by Google Chromes DevTools. We get this in the console:

```
DevTools failed to parse SourceMap: https://cdn.lr-ingest.io/@apphub:logrocket-core.js.map
DevTools failed to parse SourceMap: http://localhost:3000/main.js.map
```
Note: 
The sourcemaps stops working only after calling init: LogRocket.init('###/###')

**Comment by nverba** [comment]
Adding `import LogRocket from 'logrocket';` to our repo causes these warning to appear.

These sourceMap links are added by the `https://cdn.lr-ingest.io/logger.min.js` file, which is imported by the logrocket JavaScript SDK.

While it's not critical, it's a bit annoying.

**Comment by gabrielbezerra81** [comment]
Did you find any solution?

**Comment by connorlr** [comment]
@wiborn If you remove LogRocket, is Chrome able to parse your source map? What is the response code of the attempt to fetch your source maps?

Part of the issue may be that as of earlier this year, Chrome throws a warning for a missing source map where it did not before: https://bugs.chromium.org/p/chromium/issues/detail?id=1052872.

**Comment by eranimo** [comment]
This issue has been resolved (no upgrade necessary)

**Comment by luisfernandezelectric** [comment]
How was this issue solved? I'm facing with this issue right now
