### ISSUE TITLE
LogRocket breaks Content Security Policy (CSP) eval rule

### ISSUE THREAD

**Issue by Hongbo-Miao** [LogRocket/logrocket#15]
I tested LogRocket in one of my websites with strict Content Security Policy (CSP) policy.
 
After adding
```js
import LogRocket from 'logrocket';

LogRocket.init('app-id');
```

and deployed. LogRocket currently added the new `bloc:` file with `eval` inside causing CSP security header issue.

```json
   "csp-report":{
      "blocked-uri":"eval",
      "column-number":301122,
      "document-uri":"https://www.hongbomiao.com/",
      "line-number":8,
      "original-policy":"connect-src 'self' https://r.lr-ingest.io; default-src 'none'; font-src 'self'; frame-src 'none'; img-src 'self' data:; manifest-src 'self'; media-src 'none'; object-src 'none'; script-src 'strict-dynamic' 'nonce-l+9WU5Ace5k0Q77b2Yam8A==' 'self' https://cdn.lr-ingest.io; style-src 'self' report-uri https://www.hongbomiao.com/api/violation/report-csp-violation; upgrade-insecure-requests",
      "referrer":"",
      "source-file":"blob:https://www.hongbomiao.com/82fc6bc3-950a-f048-be84-ec1b20b08b2d",
      "violated-directive":"script-src"
   }
```

Adding `'blob:'` in **script-src** won't help.
Only adding `"'unsafe-eval'"` helps, however this will break the strict Content Security Policy (CSP) rule.

This line using `eval` in the `blob:` file currently which breaks the rule.

```js
// ...
var mod = eval('quire'.replace(/^/, 're')) (moduleName); // <- this line
if (mod && (mod.length || Object.keys(mod).length)) return mod
// ...
```

<img width="806" alt="image" src="https://user-images.githubusercontent.com/3375461/93209297-8069f380-f790-11ea-9a9c-313d110aa0c4.png">

**Comment by bmd** [comment]
hi @Hongbo-Miao - thanks for this report.

After doing some quick research, it looks like this is getting added by `protobufjs/inquire` and there's an open issue about exactly this piece of code: https://github.com/protobufjs/protobuf.js/issues/997 . 

We're investigating whether there's a workaround we can implement here, but in the meantime, you'll need to allow this eval for LogRocket to work correctly.

**Comment by Hongbo-Miao** [comment]
Thanks @bmd it would be great to let us know once this being fixed, so that we can onboard.
Otherwise we cannot risk adding LogRocket by leaving a security hole with `"'unsafe-eval'"`, which makes CSP lose its value.

**Comment by jails** [comment]
I think this issue should be reopened. Setting up a CSP with `unsafe-eval` make little sense since `unsafe-eval` can't be applied to some particular script source, if added it applies globally. 
Is some efforts has been engaged on this security concern (like moving from protobufjs to alternatives like https://github.com/mapbox/pbf) ? Or there's no plan to make LogRocket to comply on this security rule anymore ?

**Comment by danpan1** [comment]
we also suffering because of that issue. **unsafe-eval** cannot be part of our CSP. Do you plan to change the package or we need to check alternatives for LogRocket?

**Comment by Splaktar** [comment]
I agree that this needs to be re-opened and there needs to be a migration away from `protobuf/inquire`. That issue has been open for 2 years, so I doubt that it will be fixed anytime soon.

**Comment by bsell93** [comment]
Agreed. This needs to be fixed.

**Comment by syoder15** [comment]
Sorry for the delay, everyone; we have fixed the CSP violation related to eval usage. Let us know if you are still seeing them on your end, and thank you for your patience!
