### ISSUE TITLE
Official Content Security Policy (CSP) guide

### ISSUE THREAD

**Issue by Hongbo-Miao** [LogRocket/logrocket#16]
It would be great to add an official CSP guide, something like

- https://help.fullstory.com/hc/en-us/articles/360020622854-Can-I-use-Content-Security-Policy-CSP-with-FullStory-
- https://developers.google.com/tag-manager/web/csp

Just for your reference, based on my research, currently need

```sh
connect-src: https://r.lr-ingest.io
script-src: 'unsafe-eval' https://cdn.lr-ingest.io
worker-src: blob:
child-src: blob: # Safari does not support worker-src. Use child-src for backward compatible
```

to make it properly work.

Note `'unsafe-eval'` in **script-src** is a CSP security hole, which can find more details at https://github.com/LogRocket/logrocket/issues/15

**Comment by Splaktar** [comment]
Yes, official docs on this are needed 👍 

I didn't get `'unsafe-eval'` CSP errors until recently, but having to add this is really a big security problem.

Please make it a priority to resolve this.

**Comment by syoder15** [comment]
Sorry for the delay, everyone; we have fixed the CSP violation related to eval usage. Let us know if you are still seeing them on your end, and thank you for your patience!
