### ISSUE TITLE
Bad type for `TrackEventProperties` in `logrocket@1.1.0`

### ISSUE THREAD

**Issue by bengry** [LogRocket/logrocket#27]
I saw that `logrocket` v1.1.0 [was released](https://www.npmjs.com/package/logrocket) and it seems like there's a type issue with `TrackEventProperties` that hasn't existed in previous versions. This is a problem for consumers, unless you ignore type-checking libraries (using `skipLibCheck: true`), but that's not ideal of course.

The issue is that the type is defined as:
```ts
  type TrackEventProperties = {
    revenue?: number,
    [key: string]: string | number | boolean | string[] | number[] | boolean[]
  };
```

and the error is:
```console
Error: [2] [0] node_modules/logrocket/dist/types.d.ts(100,5): error TS2411: Property 'revenue' of type 'number | undefined' is not assignable to string index type 'string | number | boolean | number[] | string[] | boolean[]'.
```

Here's [a playground](https://www.typescriptlang.org/play?#code/ATAuE8AcFNgFQE4EMDGBrAogN2gO1AAoID2MCoAltAM7AC8wA3gFAggLQ64Cu0A-AC5gPALYAjaAgA0rNgG000cEOqgEFXAHMAuirUbNwAD7Du4yceBjixADbQkuS6vVa52y6IkJ3l63Ydcd1kAXwBuIA) reproducing the issue.

This can be easily fixed by changing `TrackEventProperties` to be defined as:
```ts
type TrackEventProperties = {
    [key: string]: string | number | boolean | string[] | number[] | boolean[]
} & {
    revenue?: number,
};
```
([example playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgTgQwMYGsCiA3CA7YAFOAe0jmAEsIBnKAXigG8AoKKAbRQhAC4pLg4y2AOYBdHnwHCoAHyjYArgFsARhDgyoywoQA2EBNg0TBQ1iI0KVasxq2792M4wC+UAGQNmUOBCwKIAPw8lqpwADQuANyMMQAmEEg6CD5QSITYfFAIPPDI6H74RCTkVNEIAHQ+fvLQdADk2OkAtCFqdWWVvjg1tFAAjNGMFQBm2r2sdaOEdWFQdcrJdSKRQA))

**Comment by Skwai** [comment]
This got me too

**Comment by WORMSS** [comment]
@bengry does still not break?
```ts
type TrackEventProperties = {
    [key: string]: string | number | boolean | string[] | number[] | boolean[]
} & {
    revenue?: number,
};
const a: { revenue?: number; } = { revenue: undefined }; // Perfectly valid
const b: TrackEventProperties = { revenue: undefined }; // is incompatible with index signature.
```
https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgTgQwMYGsCiA3CA7YAFOAe0jmAEsIBnKAXigG8BYAKCjagG0UIQAuKSsDhlsAcwC6-QcLFQAPlGwBXALYAjCHHlQ1hQgBsICbNukjRHcduXrNl7boNHsllgF8oAMgYt2UOBBYyhAA-Pw2GnAANO4A3CxIhNiCUAj89P6BOEqh4aqRsVAedBkBQTn8StgAJhAAZiIQ1UWFAPStUHiadRBIwPogUBgI+mTVCUkpavzwyOhB+EQk5FS0DJnlEJU19Y3Nbm0dZNQiiSpgCORqhlAA7mTAABZQIrUAHgJkotiXSgEAdEA

correct solution would be 
```ts
type TrackEventProperties = {
    revenue?: number,
    [key: string]: string | number | boolean | string[] | number[] | boolean[] | undefined
  };
```
since otherwise something like this would pass typescripts compiler but is wrong if you did more testing.
```ts
const test: string | number | boolean | string[] | number[] | boolean[] = properties['i-do-not-exist'];
if (Array.isArray(test)) { ... }
else if (typeof test == 'string') { ... }
else if (typeof test == 'boolean') { ... }
else {
  // typescript has narrowed down test to be a number, because that is all that is left on the type, not knowing that undefined is possible.
}
```

**Comment by bengry** [comment]
@WORMSS Sure. Technically it's probably more correct, but in practice this type is used as an input, to send to LR, so I don't expect to use it later on..
But again, your type is probably technically more correct.

**Comment by WORMSS** [comment]
I guess it depends if you plan on passing something like
```ts
track('blar', {
   revenue: testSomething ? 123 : undefined,
   ...props
};
```

**Comment by derekparsons718** [comment]
Still an issue in v1.2.0. This is preventing us from upgrading beyond v1.0

**Comment by bengry** [comment]
> Still an issue in v1.2.0. This is preventing us from upgrading beyond v1.0

We use `patch-package` to workaround this issue (and others like it that come in 3rd party packages from time to time). It's always a temporary fix and we're hoping to remove the patches soon, but they at least allow us to upgrade on a regular cadence for the most part.

**Comment by nlassaux** [comment]
Updated to v1.2.2, but it's still not working with that update

**Comment by Splaktar** [comment]
I'm also seeing this break my Angular build with `1.2.2`. I'm stuck on `1.0.16` for the time being.

**Comment by isaac-smolund** [comment]
Hey everyone- I know this one was hanging around for a bit, but this should be fixed as of the most recent NPM release (1.2.3); let us know if you encounter any issues. Thanks!

**Comment by WORMSS** [comment]
@bengry 
> But again, your type is probably technically more correct.

Technically correct. The best type of correct. 😄 👍

**Comment by bengry** [comment]
Issues seems to be solved in latest version. Closing this issue.
