### ISSUE TITLE
Unsave eval of Feross Buffer module.

### ISSUE THREAD

**Issue by dbauszus-glx** [LogRocket/logrocket#8]
We import logrocket in our application bundle from the Node module.

```
import LogRocket from 'logrocket';
```

Our application has tight content security policy which does not allow eval of any kind.

Log rocket works but we get a CSP unsafe eval exception warning that log rocket is trying to eval a blob source for the [Feross Buffer module](https://github.com/feross/buffer).

![image](https://user-images.githubusercontent.com/22201617/54753207-628df380-4bd8-11e9-899f-21fa8909c2cd.png)

Why is this needed? Is it possible to bundle the resource on your end? Can I bundle the resource?

Is it possible to config that the resource is not needed?

Or should I load log rocket in the browser from your server?

I already asked your support but haven't got anything back yet.

**Comment by Splaktar** [comment]
I wasn't getting this issue before, but now with the latest LogRocket SDK I'm required to add `'unsafe-eval'` to my CSP.

Can this be investigated?

**Comment by bsell93** [comment]
I am seeing this as well. Just recently. Everything was working for a month or so and then got hit with this issue last week

**Comment by dbauszus-glx** [comment]
I am glad that I am not the only one with a tight CSP. Such an easy to fix problem as well. Unfortunately it was impossible to follow this up with the log rocket engineers. I don't think the github issues are even read.

**Comment by syoder15** [comment]
Sorry for the delay, everyone; we recently took a pass fixing some other CSP violations we were seeing. Using firefox and a CSP that did not allow eval usage, we were unable to reproduce the violation related to the Feross Buffer module. Let us know if you are still seeing them on your end, and thank you for your patience!
